language: android

android:
  components:
    - build-tools-21.1.1
    - android-17
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: gradle --info build install
